# baseURL = "http://andaze.ameio.in/"
# baseURL = "https://gallant-einstein-eab8cc.netlify.app"
# baseURL = "https://hugojob.ameio.in/"
# baseURL = "https://newandaze.ameio.in/job/"
baseURL = "https://www.andaze.com/job"

languageCode = "en-us"
title = "Navigator | Responsive Multipurpose Bootstrap Hugo Template"
theme = "andazejob"
summaryLength = 10
timeout = 600000

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "G-2RBG11HF44" # your analitics ID

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "ja"

[markup.goldmark.renderer]
  unsafe = true
  
# Site Params
[params]
logo = "images/logo.png"


# Gestion des langues : JA / EN 
[[Params.listeLangues]]
code = "ja"
[[Params.listeLangues]]
code = "en"

# meta data
author = "Themefisher"
description = "This is meta description"


# Gestion des langues : FR / EN / NL / DE
[Languages]
############ 1 - Site en Japanese
[Languages.ja]
languageName = "JA"
weight = 1
languageCode = "ja-jp"
title = "採用サイト｜株式会社アンダーズ"
dateFormat = "2 January 2006"
logo = "images/logo.png"
menufixed = false
headerTitle = " 株式会社アンダーズ 採用サイト"
homeavm = ["ADVANTAGE", "VISION", "MESSAGE" ]
advantagetitle = "アンダーズで働くメリット"
visionTitle =   "ビジョンと育成方針"
messageTitle = "メッセージ"
officeid    =   "4"
officeTitle = "オフィスと周辺"
requirementTitle = "募集要項"
entryTitle  = "応募専用フォーム"
entryBoxTitle = "応募はこちらから"
footerEmpInformationTitle = "雇用情報ホーム"
footerVisionAndDevlopmenTitle = "ビジョンと育成方針"
footerLogo = "{{ `images/h_logo.png` | absURL }}"
footerOfficeTitle = "オフィスと周辺"
footerEntryTitle = "エントリー"
footerAddress = """アンダーズ株式会社 〒102-0083 東京都千代田区麹町2-10-3"""
footerMail = "contact-us@andaze.com"
footerTel =  "tel. 03-3230-0401"
footerhome = "株式会社アンダーズ：ホーム"
footerblog = ""
footerReport =  ""
Endtitle = "詳しく見る"
imagesize1 = "290"
imagesize2 = "596"
imagesize3 = "796"
imageratio = "1 1.5 2 3"
imagewidth = "1440"
fillposition = "center"
format= "webp"
srcimg = "images/imageLoading.gif"
backgroundimageposition = "center"
# Hero Area Section
[Languages.ja.params.hero]
enable  = true
advheading1 = "ADVANTAGE"
advheading2 = "アンダーズで働くメリット"
visionheading1 = "VISION"
visionheading2 = "ビジョンと育成方針"
messageheading1 = "MESSAGE"
messageheading2 = "メッセージ"
officeheading1 = "OFFICE"
officeheading2 = "オフィスと周辺"
requirementheading1 = "REQUIREMENT"
requirementheading2 = "募集要項"
button  = true
btnText = "Know More"


############# 2 - Site en ENGLISH
[Languages.en]
languageName = "EN"
weight = 2
languageCode = "en-us"
title = "Recruitment Site｜Tokyo Web Production Company/Home Page Production Company｜Hugo Job Corporation｜Hugo Job inc."
dateFormat = "January 2, 2006"
home = "EN Home"
logo = "images/logo.png"
menufixed = false
headerTitle = "Andaze, Inc. recruitment site"
advantagetitle =  "Benefits of working at Andaze"
visionTitle = "Vision and development policy"
messageTitle = "Message to applicants"
officeid = "Four"
officeTitle = "Office and surroundings"
requirementTitle = "Recruitment type and recruitment guidelines"
entryTitle  = "Application-only form"
entryBoxTitle = "Click here to apply"
footerLogo = "images/h_logo.png"
footerEmpInformationTitle = "Employment Information Home"
footerVisionAndDevlopmenTitle = "Vision and development policy"
footerOfficeTitle = "Office and surroundings"
footerEntryTitle = "entry"
footerAddress = "Co., Ltd. Andaze / 2-10-3 Kojimachi, Chiyoda Tokyo, Japan"
footerMail = "contact-us@andaze.com"
footerTel =  "Tel. 03-3230-0401"
footerhome = "Andaze Ltd. Home"
footerblog = "Andaze President's Blog"
footerReport =  "Andaze's daily report"
Endtitle = "Read more."
imagesize1 = "290"
imagesize2 = "596"
imagesize3 = "796"
imageratio = "1 1.5 2 3"
imagewidth = "1440"
fillposition = "center"
format= "webp"
srcimg = "images/imageLoading.gif"
backgroundimageposition = "center"
# cookies
[params.cookies]
enable = true
expire_days = 2

# Hero Area Section
[Languages.en.params.hero]
enable  = true
advheading1 = "ADVANTAGE"
advheading2 = "Benefits of Working at Andaze"
visionheading1 = "VISION"
visionheading2 = "Vision and Training Policy"
messageheading1 = "MESSAGE"
messageheading2 = "Message to Applicants"
officeheading1 = "OFFICE"
officeheading2 ="Office and surroundings"
requirementheading1 = "REQUIREMENT"
requirementheading2 = "Job Categories and Application Guidelines"
button  = true
btnText = "Know More"




[[menu.item]]
name    ="home"
url     ="/"
weight = 1
[[menu.item]]
name    = "merit"
url     = "merit"
weight  = 2
[[menu.item]]
name    = "vision"
url     = "vision"
weight  =  3
[[menu.item]]
name   = "message"
url    = "message"
weight = 4
[[menu.item]]
name   = "office"
url    = "office"
weight = 5
[[menu.item]]
name   = "applicationrequirements"
url    = "applicationrequirements"
weight = 6
[[menu.item]]
name   = "entry"
url    = "entry"
weight = 7

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 4
[blackfriday]
    extensions = ["hardLineBreak"]