# baseURL = "http://baigie.ameio.in/"
baseURL = "https://clever-edison-02034e.netlify.app/"
# baseURL = "http://localhost/baigie/"
# baseURL = "https://hugojob.ameio.in/"
languageCode = "en-us"
title = "Navigator | Responsive Multipurpose Bootstrap Hugo Template"
theme = "navigator-hugo"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "" # your analitics ID

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
logo = "images/logo.png"

# Gestion des langues : JP / EN 
[[Params.listeLangues]]
code = "jp"
[[Params.listeLangues]]
code = "en"

# meta data
author = "Themefisher"
description = "This is meta description"


# slider Area Images And Content
[[Languages.en.params.heading]]
srcimg = "/images/imageLoading.gif"
srcsetImg = "/images/slider/img_keyvisual_01_1403x0_resize_box.webp 2500w, /images/slider/img_keyvisual_01_768x0_resize_box.webp 1024w, /images/slider/img_keyvisual_01_320x0_resize_box.webp 640w"
dataSrcImg = "/images/slider/img_keyvisual_01.webp"
heading = "CHANGE YOURSELF WITH US, WE'LL SUPPORT YOUR CAREER."
subheading = "Vage is an environment where you can acquire the technical and work skills you need for your career. We are actively recruiting not only veterans but also enthusiastic inexperienced people. Come join us and make your life brilliant while aiming for the top of the web industry."
[[Languages.en.params.heading]]
srcimg = "/images/imageLoading.gif"
srcsetImg = "/images/slider/img_keyvisual_02_1403x0_resize_box.webp 2500w, /images/slider/img_keyvisual_02_768x0_resize_box.webp 1024w, /images/slider/img_keyvisual_02_320x0_resize_box.webp 640w"
dataSrcImg = "/images/slider/img_keyvisual_02.webp"
heading = "WE AIM AT THE FUSION OF MARKETING AND CREATIVE."
subheading = "Baisi's goal is to combine marketing and creativity at a high level. It is not a routine job of creating designs and systems according to specifications. The habit of thinking about things from a business perspective will help you grow by leaps and bounds."
[[Languages.en.params.heading]]
srcimg = "images/imageLoading.gif"
srcsetImg = "/images/slider/img_keyvisual_05_1403x0_resize_box.webp 2500w, /images/slider/img_keyvisual_05_768x0_resize_box.webp 1024w, /images/slider/img_keyvisual_05_320x0_resize_box.webp 640w"
dataSrcImg = "/images/slider/img_keyvisual_05.webp"
heading = "OUR EXCELLENT ENVIRONMENT WILL MAXIMIZE YOUR VALUE."
subheading = "The office at Baisi is a great place to work. We are a small company, so you can communicate your wishes right away. Please try to create the ideal work environment you want by yourself."
[[Languages.en.params.heading]]
srcimg = "images/imageLoading.gif"
srcsetImg = "/images/slider/img_keyvisual_04_1403x0_resize_box.webp 2500w, /images/slider/img_keyvisual_04_768x0_resize_box.webp 1024w, /images/slider/img_keyvisual_04_320x0_resize_box.webp 640w"
dataSrcImg = "/images/slider/img_keyvisual_04.webp"
heading = "WE'RE IN THE GROWTH PHASE, YOUR FUTURE IS SPREADING."
subheading = "Bayzi has a clear vision for the future of the industry and the company. We are currently in the phase of increasing the number of talented staff and creating the foundation for future development. Because we are still developing, you can become the core of the company if you choose."

[[Languages.jp.params.heading]]
srcimg = "images/imageLoading.gif"
srcsetImg = "/images/slider/img_keyvisual_01_1403x0_resize_box.webp 2500w, /images/slider/img_keyvisual_01_768x0_resize_box.webp 1024w, /images/slider/img_keyvisual_01_320x0_resize_box.webp 640w"
dataSrcImg = "/images/slider/img_keyvisual_01.webp"
heading = "私たちと一緒に自分を変えよう, あなたのキャリアをサポートします。"
subheading = "ベイジは、あなたのキャリアに必要な技術力と仕事力が身に付く環境です。ベテランだけではなく、熱意ある未経験者も積極的に採用しています。 私たちとともに、Web業界の頂点を目指しながら人生を輝かしいものにしませんか。"
[[Languages.jp.params.heading]]
srcimg = "images/imageLoading.gif"
srcsetImg = "/images/slider/img_keyvisual_02_1403x0_resize_box.webp 2500w, /images/slider/img_keyvisual_02_768x0_resize_box.webp 1024w, /images/slider/img_keyvisual_02_320x0_resize_box.webp 640w"
dataSrcImg = "/images/slider/img_keyvisual_02.webp"
heading = "私たちはマーケティングとクリエイティブの融合を目指し。"
subheading = "ベイジが目指すのは、マーケティングとクリエイティブの高次元での融合です。 仕様通りにデザインやシステムを作るルーチンワークではありません。 ビジネス発想で物事を考える習慣が、あなたを飛躍的に成長させるでしょう。"
[[Languages.jp.params.heading]]
srcimg = "images/imageLoading.gif"
srcsetImg = "/images/slider/img_keyvisual_05_1403x0_resize_box.webp 2500w, /images/slider/img_keyvisual_05_768x0_resize_box.webp 1024w, /images/slider/img_keyvisual_05_320x0_resize_box.webp 640w"
dataSrcImg = "/images/slider/img_keyvisual_05.webp"
heading = "優れた環境でお客様の価値を最大化する。"
subheading = "ベイジのオフィスには、仕事がしやすい環境が整っています。 小さな会社なので、希望はすぐに伝えることができます。 あなたの望む理想の職場環境を、あなた自身の力で作ってみてください。"
[[Languages.jp.params.heading]]
srcimg = "images/imageLoading.gif"
srcsetImg = "/images/slider/img_keyvisual_04_1403x0_resize_box.webp 2500w, /images/slider/img_keyvisual_04_768x0_resize_box.webp 1024w, /images/slider/img_keyvisual_04_320x0_resize_box.webp 640w"
dataSrcImg = "/images/slider/img_keyvisual_04.webp"
heading = "我々は成長段階にある, あなたの未来は広がっている。"
subheading = "ベイジは、業界や会社の未来に明確なビジョンを持っています。 今は、優秀なスタッフを増やし、将来の発展の基盤を作るフェーズ。 発展途上だから、あなた次第で会社の中核にだってなることができます。"

# Gestion des langues : FR / EN / NL / DE
[Languages]
############ 1 - Site en Japanese
[Languages.jp]
languageName = "JP"
weight = 1
languageCode = "jp-jp"
title = "採用サイト｜東京のWeb制作会社・ホームページ制作会社｜株式会社ベイジ｜Hugo Job inc."
dateFormat = "2 January 2006"
logo = "images/logo.png"
menufixed = false
headerTitle = " 株式会社ベイジ 採用サイト"
homeavm = ["ADVANTAGE", "VISION", "MESSAGE" ]
advantagetitle = "ベイジで働くメリット"
visionTitle =   "ビジョンと育成方針"
messageTitle = "応募者へのメッセージ"
officeid    =   "4"
officeTitle = "オフィスと周辺"
requirementTitle = "募集職種と募集要項"
entryTitle  = "応募専用フォーム"
entryBoxTitle = ">応募はこちらから"
footerEmpInformationTitle = "雇用情報ホーム"
footerVisionAndDevlopmenTitle = "ビジョンと育成方針"
footerLogo = "{{ `images/h_logo.png` | absURL }}"
footerOfficeTitle = "オフィスと周辺"
footerEntryTitle = "エントリー"
footerAddress = "株式会社ベイジ / Hugo Job inc.〒155-0033東京都世田谷区代田6-6-1TOKYU REIT下北沢スクエア 3F"
footerMail = "mail.info@Hugo Job.me"
footerTel =  "tel. 03-6407-8750"
footerfax = "fax. 03-6407-8751"
footerhome = "株式会社ベイジ：ホーム"
footerblog = "ベイジ社長ブログ"
footerReport =  "ベイジの日報"
Endtitle = "> 詳しく見る"

# Hero Area Section
[Languages.jp.params.hero]
enable  = true
advheading1 = "ADVANTAGE"
advheading2 = "ベイジで働くメリット"
visionheading1 = "VISION"
visionheading2 = "ビジョンと育成方針"
messageheading1 = "MESSAGE"
messageheading2 = "応募者へのメッセージ"
officeheading1 = "OFFICE"
officeheading2 = "オフィスと周辺"
requirementheading1 = "REQUIREMENT"
requirementheading2 = "募集職種・募集要項"
button  = true
btnText = "Know More"


############# 2 - Site en ENGLISH
[Languages.en]
languageName = "EN"
weight = 2
languageCode = "en-us"
title = "Recruitment Site｜Tokyo Web Production Company/Home Page Production Company｜Hugo Job Corporation｜Hugo Job inc."
dateFormat = "January 2, 2006"
home = "EN Home"
logo = "images/logo.png"
menufixed = false
headerTitle = "Beiji Co., Ltd. recruitment site"
advantagetitle =  "Benefits of working at Bage"
visionTitle = "Vision and development policy"
messageTitle = "Message to applicants"
officeid = "Four"
officeTitle = "Office and surroundings"
requirementTitle = "Recruitment type and recruitment guidelines"
entryTitle  = "Application-only form"
entryBoxTitle = "> Click here to apply"
footerLogo = "images/h_logo.png"
footerEmpInformationTitle = "Employment Information Home"
footerVisionAndDevlopmenTitle = "Vision and development policy"
footerOfficeTitle = "Office and surroundings"
footerEntryTitle = "entry"
footerAddress = "Co., Ltd. Beiji / Hugo Job inc.Yubinbango155-0033, Setagaya-ku, Tokyo Shirota 6-6-1, TOKYU REIT Shimokitazawa Square 3F"
footerMail = "Mail.info@Hugo Job.me"
footerTel =  "Tel. 03-6407-8750"
footerfax = "Fax. 03-6407-8751"
footerhome = "Beiji Co., Ltd .: Home"
footerblog = "Beiji President's Blog"
footerReport =  "Beiji's daily report"
Endtitle = "> Read more."

# cookies
[params.cookies]
enable = true
expire_days = 2

# Hero Area Section
[Languages.en.params.hero]
enable  = true
advheading1 = "ADVANTAGE"
advheading2 = "Benefits of Working at Vage"
visionheading1 = "VISION"
visionheading2 = "Vision and Training Policy"
messageheading1 = "MESSAGE"
messageheading2 = "Message to Applicants"
officeheading1 = "OFFICE"
officeheading2 ="Office and surroundings"
requirementheading1 = "REQUIREMENT"
requirementheading2 = "Job Categories and Application Guidelines"
button  = true
btnText = "Know More"




[[menu.item]]
name    ="home"
url     ="/"
weight = 1
[[menu.item]]
name    = "merit"
url     = "merit"
weight  = 2
[[menu.item]]
name    = "vision"
url     = "vision"
weight  =  3
[[menu.item]]
name   = "message"
url    = "message"
weight = 4
[[menu.item]]
name   = "office"
url    = "office"
weight = 5
[[menu.item]]
name   = "applicationrequirements"
url    = "applicationrequirements"
weight = 6
[[menu.item]]
name   = "entry"
url    = "entry"
weight = 7
