# baseURL = "http://andaze.ameio.in/"
# baseURL = "https://gallant-einstein-eab8cc.netlify.app"
# baseURL = "https://hugojob.ameio.in/"
# baseURL = "https://newandaze.ameio.in/job/"
baseURL = "https://job.andaze.com/"